server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  ai:
    openai:
      api-key: @dashscope.api.key@
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: qwen-plus
          temperature: 0.7
          maxTokens: 5000

      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode/
        api-key: @dashscope.api.key@
        options:
          model: text-embedding-v4
          dimmension: 1024

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dodo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8 # 记得改成你自己的
    username: root # 记得改成你自己的
    password: root # 记得改成你自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000

  # MyBatis-Plus 配置
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

minio:
  url: http://192.168.11.163:19000/   # 记得改成你自己的
  accessKey: minioadmin # 记得改成你自己的
  secretKey: minioadmin # 记得改成你自己的
  bucketName: rag-test2
  endpoint: http://192.168.11.163:19000/

embeddings:
  store:
    host: 192.168.113.52   # 记得改成你自己的
    port: 5433   # 记得改成你自己的
    database: vector_store   # 记得改成你自己的
    user: postgres   # 记得改成你自己的
    password: postgres   # 记得改成你自己的

# Tavily 搜索引擎配置
tavily:
  api-key: tvly-dev-DXXXXXXXXX  # 记得改成你自己的
  mcp-url: https://mcp.tavily.com/mcp/

grsai:
  nanobanana:
    api-key: sk-ec99XXXXXXXXXXXXXX # 记得改成你自己的

logging:
  level:
    org:
      springframework:
        ai: INFO
    io:
      modelcontextprotocol:
        client: ERROR
