<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.6</version>
        <relativePath/>
    </parent>

    <groupId>cn.hollis.llm</groupId>
    <artifactId>LLMentor</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>LLMentor</name>
    <packaging>pom</packaging>
    <description>Hollis出品的LLM课程，像一个Mentor一样带你学习LLM内容</description>

    <modules>
        <module>springai</module>
        <module>rag</module>
        <module>mcp/mcp-server-sse</module>
        <module>mcp/mcp-server-stdio</module>
        <module>mcp/mcp-server-streamable</module>
        <module>mcp/mcp-client</module>
        <module>mcp/mcp-server-sse-https</module>
        <module>agent/general-agent</module>
        <module>function-call</module>
        <module>langchain4j</module>
        <module>agent/dodo-agent</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring.ai.version>1.1.0</spring.ai.version>
        <fastjson.version>2.0.43</fastjson.version>
        <spring.ai.alibaba.version>1.1.2.0</spring.ai.alibaba.version>
        <!-- 统一配置API Key ，记得改成你自己的-->
        <dashscope.api.key>272967929bb0499088d3928f56a55e0c.7raZsTOprBBiypHO</dashscope.api.key>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.alibaba.cloud.ai</groupId>
                <artifactId>spring-ai-alibaba-bom</artifactId>
                <version>${spring.ai.alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring.ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
