spring:
  application:
    name: LLMentor_SpringAI
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
    dashscope:
      api-key: @dashscope.api.key@
    chat:
      memory:
        repository:
          jdbc:
            platform: mysql
            initialization-mode: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/spring_ai_db2?useUnicode=true&characterEncoding=UTF-8  # 记得改成你自己的
    username: llmentor  # 记得改成你自己的
    password: llmentor666  # 记得改成你自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      continue-on-error: true  # SQL初始化失败时继续启动
server:
  port: 8000